bd: rentacar
login: rent
senha: rent

CREATE TABLE TB_USUARIOS (
	"ID_USUARIO" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
	(START WITH 0, INCREMENT BY 1),
	"NOME_USUARIO" VARCHAR(255) NOT NULL,
	"RG" VARCHAR(12) NOT NULL,
	"CPF" VARCHAR(14) NOT NULL,
	"LOGIN" VARCHAR(20) NOT NULL,
	"SENHA" VARCHAR(20) NOT NULL,
	"ATIVO" BOOLEAN NOT NULL,
	"CARGO_ID" INTEGER NOT NULL,
	"FILIAL_ID" INTEGER NOT NULL);

CREATE TABLE TB_VEICULOS (
	"ID_VEICULO" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
	(START WITH 0, INCREMENT BY 1),
	"NOME_VEICULO" VARCHAR(50) NOT NULL,
	"RENAVAM_VEICULO" VARCHAR(11) NOT NULL,
	"PLACA_VEICULO" VARCHAR(7) NOT NULL,
	"COR_ID" INTEGER,
	"MARCA_ID" INTEGER,
	"CATEGORIA_ID" INTEGER,
	"FILIAL_ID" INTEGER);

CREATE TABLE TB_CADASTRO_CLIENTE (
	"ID_CLIENTE" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
	(START WITH 0, INCREMENT BY 1),
	"NOME_CLIENTE" VARCHAR(255) NOT NULL,
	"RG" VARCHAR(12) NOT NULL,
	"CPF" VARCHAR(14) NOT NULL,
	"CNH" VARCHAR(11) NOT NULL, 
	"DATA_NASCIMENTO" DATE NOT NULL,
	"DATA_CADASTRO" DATE NOT NULL);

CREATE TABLE TB_CONTRATO (
	"ID_CONTRATO" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
	(START WITH 0, INCREMENT BY 1),
	"CLIENTE_ID" INTEGER NOT NULL,
	"USUARIO_ID" INTEGER NOT NULL,
	"VEICULO_ID" INTEGER NOT NULL,
	"DATA_RETIRADA" DATE NOT NULL,
	"DATA_DEVOLUCAO" DATE NOT NULL,
	"QUANTIDADE_DIARIAS" INT NOT NULL,
	"TOTAL_RESERVA" DOUBLE NOT NULL, 
	"SALDO_DA_RESERVA" DOUBLE NOT NULL, 
	"FILIAL_ID" INTEGER NOT NULL,
	"DATA_ABERTURA" DATE,
	"DATA_FECHAMENTO" DATE,
	"ABERTO" BOOLEAN NOT NULL);

CREATE TABLE TB_MARCAS_VEICULOS (
	"ID_MARCA" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
	(START WITH 0, INCREMENT BY 1),
	"DESCRICAO_MARCA" VARCHAR(55) NOT NULL);



CREATE TABLE TB_CATEGORIA_VEICULOS (
	"ID_CATEGORIA" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
	(START WITH 0, INCREMENT BY 1),
	"DESCRICAO_CATEGORIA" VARCHAR(55) NOT NULL,
	"VALOR_CATEGORIA" DECIMAL NOT NULL);
	
	

	
CREATE TABLE TB_CORES (
	"ID_COR" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
	(START WITH 0, INCREMENT BY 1),
	"DESCRICAO_COR" VARCHAR(55) NOT NULL);
	


CREATE TABLE TB_CARGOS(
	"ID_CARGO" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
	(START WITH 0, INCREMENT BY 1),
	"DESCRICAO_CARGO" VARCHAR(55) NOT NULL);
	


CREATE TABLE TB_CIDADES(
	"ID_CIDADE" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
	(START WITH 0, INCREMENT BY 1),
	"DESCRICAO_CIDADE" VARCHAR(55) NOT NULL);
	



CREATE TABLE TB_ESTADOS(
	"ID_ESTADO" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
	(START WITH 0, INCREMENT BY 1),
	"DESCRICAO_ESTADO" VARCHAR(55) NOT NULL);
	


CREATE TABLE TB_FILIAIS(
	"ID_FILIAL" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
	(START WITH 0, INCREMENT BY 1),
        "NOME_LOJA" VARCHAR(100) NOT NULL,
	"ENDERECO_FILIAL" VARCHAR(255) NOT NULL,
	"CIDADE_ID" INTEGER,
	"ESTADO_ID" INTEGER,
	"GERENTE_ID" INTEGER);
	


CREATE TABLE TB_FORMA_DE_PAGAMENTOS(
	"ID_FORMA_PAGAMENTO" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
	(START WITH 0, INCREMENT BY 1),
	"TIPO_PAGAMENTO" VARCHAR(55) NOT NULL);



CREATE TABLE TB_ESTOQUE(
	"ID_ESTOQUE" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
	(START WITH 0, INCREMENT BY 1), 
	"VEICULO_ID" INTEGER NOT NULL,
	"QUANTIDADE" INTEGER,
	"FILIAL_ID" INTEGER);

CREATE TABLE TB_HISTORICO_ACESSO(
	"ID_LOG" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
	(START WITH 0, INCREMENT BY 1), 
	"USUARIO_ID" INTEGER NOT NULL,
	"TIPO_LOG_ID" INTEGER NOT NULL,
	"DATA_SISTEMA" DATE NOT NULL,
	"HORA_SISTEMA" TIME NOT NULL);

CREATE TABLE TB_TIPO_LOG(
        "ID_TIPO_LOG" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
	(START WITH 0, INCREMENT BY 1),
        "TIPO_LOG" VARCHAR(30) NOT NULL);



CREATE TABLE TB_PAGAMENTOS(
	"ID_PAGAMENTOS" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY
	(START WITH 0, INCREMENT BY 1),
	"CONTRATO_ID" INTEGER NOT NULL,
	"FORMA_PAGAMENTO_ID" INTEGER NOT NULL,
	"VALOR_PAGO" DOUBLE NOT NULL);
	
0-- INSERT INTO TB_TIPO_LOG (TIPO_LOG) VALUES ('LOGIN');
1-- INSERT INTO TB_TIPO_LOG (TIPO_LOG) VALUES ('LOGOUT');	
2-- INSERT INTO TB_TIPO_LOG (TIPO_LOG) VALUES ('INCLUSÃO DE USUÁRIO');
3-- INSERT INTO TB_TIPO_LOG (TIPO_LOG) VALUES ('ALTERAÇÃO DE USUÁRIO');
4-- INSERT INTO TB_TIPO_LOG (TIPO_LOG) VALUES ('BUSCA DE USUÁRIO');
5-- INSERT INTO TB_TIPO_LOG (TIPO_LOG) VALUES ('VIEW LISTA DE USUÁRIOS');
6-- INSERT INTO TB_TIPO_LOG (TIPO_LOG) VALUES ('INCLUSÃO DE CLIENTE');
7-- INSERT INTO TB_TIPO_LOG (TIPO_LOG) VALUES ('ALTERAÇÃO DE CLIENTE');
8-- INSERT INTO TB_TIPO_LOG (TIPO_LOG) VALUES ('BUSCA DE CLIENTE');
9-- INSERT INTO TB_TIPO_LOG (TIPO_LOG) VALUES ('VIEW LISTA DE CLIENTES');
10-- INSERT INTO TB_TIPO_LOG (TIPO_LOG) VALUES ('INCLUSÃO DE CONTRATO');
11-- INSERT INTO TB_TIPO_LOG (TIPO_LOG) VALUES ('ENCERRAMENTO DE CONTRATO');
12-- INSERT INTO TB_TIPO_LOG (TIPO_LOG) VALUES ('BUSCAR CONTRATO');
13-- INSERT INTO TB_TIPO_LOG (TIPO_LOG) VALUES ('VIEW LISTA CONTRATOS');
14-- INSERT INTO TB_TIPO_LOG (TIPO_LOG) VALUES ('INCLUSÃO DE PAGAMENTOS');
15-- INSERT INTO TB_TIPO_LOG (TIPO_LOG) VALUES ('VIEW RELATORIOS');
INSERT INTO TB_FILIAIS (NOME_LOJA, ENDERECO_FILIAL, CIDADE_ID, ESTADO_ID) VALUES ('LOJA SÃO PAULO', 'AV CONSOLAÇÃO, 100', 0, 0);
INSERT INTO TB_FILIAIS (NOME_LOJA, ENDERECO_FILIAL, CIDADE_ID, ESTADO_ID) VALUES ('LOJA RIO DE JANEIRO', 'AV PRINCESA ISABEL, 100', 1, 1);
INSERT INTO TB_FILIAIS (NOME_LOJA, ENDERECO_FILIAL, CIDADE_ID, ESTADO_ID) VALUES ('LOJA BELO HORIZONTE', 'AV DO CONTORNO, 100', 2, 2);
INSERT INTO TB_FILIAIS (NOME_LOJA, ENDERECO_FILIAL, CIDADE_ID, ESTADO_ID) VALUES ('LOJA PORTO ALEGRE', 'AV INDEPENDENCIA, 100', 3, 3);
INSERT INTO TB_FORMA_DE_PAGAMENTOS (TIPO_PAGAMENTO) VALUES ('DINHEIRO');
INSERT INTO TB_FORMA_DE_PAGAMENTOS (TIPO_PAGAMENTO) VALUES ('CARTÃO');
INSERT INTO TB_ESTADOS (DESCRICAO_ESTADO) VALUES ('SP');
INSERT INTO TB_ESTADOS (DESCRICAO_ESTADO) VALUES ('RJ');
INSERT INTO TB_ESTADOS (DESCRICAO_ESTADO) VALUES ('MG');
INSERT INTO TB_ESTADOS (DESCRICAO_ESTADO) VALUES ('RS');
INSERT INTO TB_CIDADES (DESCRICAO_CIDADE) VALUES ('SÃO PAULO');
INSERT INTO TB_CIDADES (DESCRICAO_CIDADE) VALUES ('RIO DE JANEIRO');
INSERT INTO TB_CIDADES (DESCRICAO_CIDADE) VALUES ('BELO HORIZONTE');
INSERT INTO TB_CIDADES (DESCRICAO_CIDADE) VALUES ('PORTO ALEGRE');
INSERT INTO TB_CORES (DESCRICAO_COR) VALUES ('BRANCA');
INSERT INTO TB_CORES (DESCRICAO_COR) VALUES ('PRETA');
INSERT INTO TB_CORES (DESCRICAO_COR) VALUES ('PRATA');
INSERT INTO TB_CARGOS (DESCRICAO_CARGO) VALUES ('ATENDENTE');
INSERT INTO TB_CARGOS (DESCRICAO_CARGO) VALUES ('GERENTE');
INSERT INTO TB_CARGOS (DESCRICAO_CARGO) VALUES ('DIRETOR');
INSERT INTO TB_MARCAS_VEICULOS (DESCRICAO_MARCA) VALUES ('FORD');
INSERT INTO TB_MARCAS_VEICULOS (DESCRICAO_MARCA) VALUES ('FIAT');
INSERT INTO TB_MARCAS_VEICULOS (DESCRICAO_MARCA) VALUES ('CHEVROLET');
INSERT INTO TB_MARCAS_VEICULOS (DESCRICAO_MARCA) VALUES ('VW');
INSERT INTO TB_MARCAS_VEICULOS (DESCRICAO_MARCA) VALUES ('RENAULT');
INSERT INTO TB_CATEGORIA_VEICULOS (DESCRICAO_CATEGORIA, VALOR_CATEGORIA) VALUES ('ECONOMICO', 100.00);
INSERT INTO TB_CATEGORIA_VEICULOS (DESCRICAO_CATEGORIA, VALOR_CATEGORIA) VALUES ('INTERMEDIARIO', 150.00);
INSERT INTO TB_CATEGORIA_VEICULOS (DESCRICAO_CATEGORIA, VALOR_CATEGORIA) VALUES ('SUPERIOR', 200.00);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('KA', '12345678912', 'AAA1111', 1,0,0,0);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('KA', '22345678912', 'AAA1114', 1,0,0,0);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('KA', '32345678912', 'AAA1115', 1,0,0,0);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('PALIO', '42345678912', 'AAA1112', 1,1,0,0);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('PALIO', '52345678912', 'AAA1116', 1,1,0,0);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('PALIO', '62345678912', 'AAA1117', 1,1,0,0);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('SANDERO', '72345678912', 'AAA1113', 1,4,1,0);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('SANDERO', '82345678912', 'AAA1118', 1,4,1,0);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('SANDERO', '92345678912', 'AAA1119', 1,4,1,0);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('CRUZE', '13345678912', 'AAA1120', 1,2,2,0);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('KA', '13345678912', 'AAA1121', 1,0,0,1);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('KA', '23345678912', 'AAA1124', 1,0,0,1);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('KA', '33345678912', 'AAA1125', 1,0,0,1);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('PALIO', '43345678912', 'AAA1122', 1,1,0,1);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('PALIO', '53345678912', 'AAA1126', 1,1,0,1);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('PALIO', '63345678912', 'AAA1127', 1,1,0,1);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('SANDERO', '73345678912', 'AAA1123', 1,4,1,1);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('SANDERO', '83345678912', 'AAA1128', 1,4,1,1);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('SANDERO', '93345678912', 'AAA1129', 1,4,1,1);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('CRUZE', '03345678912', 'AAA1130', 1,2,2,1);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('KA', '14345678912', 'AAA1131', 1,0,0,2);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('KA', '24345678912', 'AAA1134', 1,0,0,2);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('KA', '34345678912', 'AAA1135', 1,0,0,2);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('PALIO', '44345678912', 'AAA1132', 1,1,0,2);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('PALIO', '54345678912', 'AAA1136', 1,1,0,2);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('PALIO', '64345678912', 'AAA1137', 1,1,0,2);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('SANDERO', '74345678912', 'AAA1133', 1,4,1,2);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('SANDERO', '84345678912', 'AAA1138', 1,4,1,2);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('SANDERO', '94345678912', 'AAA1139', 1,4,1,2);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('CRUZE', '04345678912', 'AAA1140', 1,2,2,2);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('KA', '15345678912', 'AAA1141', 1,0,0,3);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('KA', '25345678912', 'AAA1144', 1,0,0,3);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('KA', '35345678912', 'AAA1145', 1,0,0,3);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('PALIO', '45345678912', 'AAA1142', 1,1,0,3);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('PALIO', '55345678912', 'AAA1146', 1,1,0,3);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('PALIO', '65345678912', 'AAA1147', 1,1,0,3);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('SANDERO', '75345678912', 'AAA1143', 1,4,1,3);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('SANDERO', '85345678912', 'AAA1148', 1,4,1,3);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('SANDERO', '95345678912', 'AAA1149', 1,4,1,3);
INSERT INTO TB_VEICULOS (NOME_VEICULO, RENAVAM_VEICULO, PLACA_VEICULO, COR_ID, MARCA_ID, CATEGORIA_ID, FILIAL_ID) VALUES ('CRUZE', '05345678912', 'AAA1150', 1,2,2,3);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (0, 1, 0);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (1, 1, 0);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (2, 1, 0);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (3, 1, 0);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (4, 1, 0);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (5, 1, 0);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (6, 1, 0);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (7, 1, 0);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (8, 1, 0);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (9, 1, 0);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (10, 1, 0);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (11, 1, 1);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (12, 1, 1);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (13, 1, 1);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (14, 1, 1);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (15, 1, 1);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (16, 1, 1);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (17, 1, 1);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (18, 1, 1);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (19, 1, 1);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (20, 1, 1);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (21, 1, 3);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (22, 1, 3);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (23, 1, 3);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (24, 1, 3);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (25, 1, 3);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (26, 1, 3);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (27, 1, 3);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (28, 1, 3);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (29, 1, 3);
INSERT INTO TB_ESTOQUE (VEICULO_ID, QUANTIDADE, FILIAL_ID) VALUES (30, 1, 3);
INSERT INTO TB_USUARIOS (NOME_USUARIO, RG, CPF, LOGIN, SENHA, ATIVO, CARGO_ID, FILIAL_ID) VALUES ('YGOR PESSOA', '111111111', '11111111111', 'y', 'y', true, 0, 0);
INSERT INTO TB_USUARIOS (NOME_USUARIO, RG, CPF, LOGIN, SENHA, ATIVO, CARGO_ID, FILIAL_ID) VALUES ('YGOR PESSOA', '111111111', '11111111111', 'y', 'y', true, 0, 1);
INSERT INTO TB_USUARIOS (NOME_USUARIO, RG, CPF, LOGIN, SENHA, ATIVO, CARGO_ID, FILIAL_ID) VALUES ('YGOR PESSOA', '111111111', '11111111111', 'y', 'y', true, 0, 2);
INSERT INTO TB_USUARIOS (NOME_USUARIO, RG, CPF, LOGIN, SENHA, ATIVO, CARGO_ID, FILIAL_ID) VALUES ('YGOR PESSOA', '111111111', '11111111111', 'y', 'y', true, 0, 3);
INSERT INTO TB_USUARIOS (NOME_USUARIO, RG, CPF, LOGIN, SENHA, ATIVO, CARGO_ID, FILIAL_ID) VALUES ('WELLINGTON OLIVEIRA', '222222222', '22222222222', 'w', 'w', true, 1, 0);
INSERT INTO TB_USUARIOS (NOME_USUARIO, RG, CPF, LOGIN, SENHA, ATIVO, CARGO_ID, FILIAL_ID) VALUES ('WELLINGTON OLIVEIRA', '222222222', '22222222222', 'w', 'w', true, 1, 1);
INSERT INTO TB_USUARIOS (NOME_USUARIO, RG, CPF, LOGIN, SENHA, ATIVO, CARGO_ID, FILIAL_ID) VALUES ('WELLINGTON OLIVEIRA', '222222222', '22222222222', 'w', 'w', true, 1, 2);
INSERT INTO TB_USUARIOS (NOME_USUARIO, RG, CPF, LOGIN, SENHA, ATIVO, CARGO_ID, FILIAL_ID) VALUES ('WELLINGTON OLIVEIRA', '222222222', '22222222222', 'w', 'w', true, 1, 3);
INSERT INTO TB_USUARIOS (NOME_USUARIO, RG, CPF, LOGIN, SENHA, ATIVO, CARGO_ID, FILIAL_ID) VALUES ('MATHEUS SOARES', '333333333', '33333333333', 'm', 'm', true, 1, 0);
INSERT INTO TB_USUARIOS (NOME_USUARIO, RG, CPF, LOGIN, SENHA, ATIVO, CARGO_ID, FILIAL_ID) VALUES ('MATHEUS SOARES', '333333333', '33333333333', 'm', 'm', true, 1, 1);
INSERT INTO TB_USUARIOS (NOME_USUARIO, RG, CPF, LOGIN, SENHA, ATIVO, CARGO_ID, FILIAL_ID) VALUES ('MATHEUS SOARES', '333333333', '33333333333', 'm', 'm', true, 1, 2);
INSERT INTO TB_USUARIOS (NOME_USUARIO, RG, CPF, LOGIN, SENHA, ATIVO, CARGO_ID, FILIAL_ID) VALUES ('MATHEUS SOARES', '333333333', '33333333333', 'm', 'm', true, 1, 3);

